### ISSUE TITLE
User-Agent: iClock Proxy

### ISSUE THREAD

**Issue by mdestafadilah** [saifulcoder/adms-server-ZKTeco#4]
Halo pak, kenapa di VPS server saya muncul ini ya pak, pada saat handshake mesin dan server
![18-07-2024 16-42-03](https://github.com/user-attachments/assets/91345001-c9f8-4249-a6ec-408b41dca8e8)

saya uji pake postman masuk, tp dari mesin ke aplikasi gak bisa pak, apakah di bapak aman?

**Comment by saifulcoder** [comment]
Ada settingan kolom yg is not null harus dibikin nullable 
Sudah saya update coba dicek lg
Kebetulan saya jg lg mau update script ini dan sudah terinstall di vps dummy
kalau mau bisa email saya untuk lebih lanjut saiful.coder@gmail.com

**Comment by mdestafadilah** [comment]
siap pak, nanti saya email ya, ini email saya pak. saya kirim ya. mdestafadilah@gmail.com
