### ISSUE TITLE
500 Error Code

### ISSUE THREAD

**Issue by mdestafadilah** [saifulcoder/adms-server-ZKTeco#5]
<img width="421" alt="27-07-2024 04-23-05" src="https://github.com/user-attachments/assets/41d68649-9b43-4b25-8cc4-941170799e0b">

apakah ada yang salah dengan configurasi server vps nyah pak?

**Comment by mdestafadilah** [comment]
getContent() empty ... kalo all() dapat pak

![Uploading 27-07-2024 04-42-34.png…]()

**Comment by saifulcoder** [comment]
Siap pak terima kasih masukkannya saya update

**Comment by mdestafadilah** [comment]
mantap, solved ya pak.
