### ISSUE TITLE
Webhook

### ISSUE THREAD

**Issue by mdestafadilah** [saifulcoder/adms-server-ZKTeco#7]
Fiture webhook sepertinya menarik pak, kayaknya blm ada ya?

**Comment by saifulcoder** [comment]
Webhook untuk apa pak?
Yg handshake kemaren gmn?
punya manual book api nya g pak?

**Comment by mdestafadilah** [comment]
> Webhook untuk apa pak?
> Yg handshake kemaren gmn?
> punya manual book api nya g pak?

Misal hook kirim notif ke tele atau whatsapp. 

Ada pak, saya share di blog saya. 

https://topidesta.my.id

**Comment by saifulcoder** [comment]
saya rasa ini sudah cukup pak
karena fungsi utama sudah terpenuhi
silahkan kembangkan sendiri kelanjutannya
